-- apply changes
create table pigeons (
  id                            integer generated by default as identity not null,
  url                           varchar(255),
  allowed                       boolean default false not null,
  cutepigeons_user_uuid         uuid,
  constraint pk_pigeons primary key (id)
);

create table cutepigeons_users (
  uuid                          uuid not null,
  display_name                  varchar(255),
  constraint pk_cutepigeons_users primary key (uuid)
);

-- foreign keys and indices
create index ix_pigeons_cutepigeons_user_uuid on pigeons (cutepigeons_user_uuid);
alter table pigeons add constraint fk_pigeons_cutepigeons_user_uuid foreign key (cutepigeons_user_uuid) references cutepigeons_users (uuid) on delete restrict on update restrict;

